name: 'rates-api'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      - FLASK_APP
      - FLASK_ENV
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - LOGGING_CONFIG
    command: flask run --host=0.0.0.0 --port=5001

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/rates.sql:/docker-entrypoint-initdb.d/rates.sql
    ports:
      - "5432:5432"
